### ISSUE TITLE
Include more formal definition?

### ISSUE THREAD

**Issue by August-Alm** [maxbryarsmansell/cFMC#1]
Hi! I've glanced through the papers on the FMC and find the idea of extending it with first class locations intriguing. Perhaps you could include a definition of the grammar for the cFMC (the minimal core calculus) and its beta-reduction rules in the README of the repository?

**Comment by bmqn** [comment]
Hi @August-Alm, I'm very happy to see that there is still interest in the work I did for this! I'm looking into the best way of getting this made available, since there is a lot of fantastic stuff here. In fact, I'm considering the possibility of including the full dissertation since the formal definitions I wrote often reference back to previous sections for definitions and terminology etc.

**Comment by bmqn** [comment]
Hi @August-Alm, I've added the full thesis to the root of the repository. Chapter 4 is where the formal definitions  are given. I hope it's an interesting read!
